BEGIN TRANSACTION;

-- adds trivial stress to monosyllabic words
UPDATE lemma
SET lemma_stressed = stress_syllable(lemma_stressed, 1)
WHERE num_syllables = 1 AND num_stresses = 0;

-- adds stress to diminutive lemmata
UPDATE lemma
SET lemma_stressed = 
        stress_syllable(lemma.lemma_stressed, 
            find_nth_stressed_syllable_rev(
                IFNULL(
                    (SELECT l2.lemma_stressed FROM lemma l2 WHERE l2.lemma_id = lemma.derivative_id AND l2.num_stresses > 0),
                    lemma.lemma_stressed
                ), 1
            )
        )
WHERE lemma.derivative_type = 'diminutive' AND
    lemma.num_stresses = 0 AND
    lemma.derivative_id IS NOT NULL;

-- stress some numerals manually
UPDATE lemma SET lemma_stressed = 'два`йсет' WHERE lemma_id = 102901;
UPDATE lemma SET lemma_stressed = 'двана`йсет' WHERE lemma_id = 102903;
UPDATE lemma SET lemma_stressed = 'деветна`йсет' WHERE lemma_id = 102906;
UPDATE lemma SET lemma_stressed = 'едина`йсет' WHERE lemma_id = 102909;
UPDATE lemma SET lemma_stressed = 'осемна`йсет' WHERE lemma_id = 102912;
UPDATE lemma SET lemma_stressed = 'петна`йсет' WHERE lemma_id = 102915;
UPDATE lemma SET lemma_stressed = 'седемна`йсет' WHERE lemma_id = 102918;
UPDATE lemma SET lemma_stressed = 'три`йсет' WHERE lemma_id = 102920;
UPDATE lemma SET lemma_stressed = 'трина`йсет' WHERE lemma_id = 102922;
UPDATE lemma SET lemma_stressed = 'четири`йсет' WHERE lemma_id = 102925;
UPDATE lemma SET lemma_stressed = 'шестна`йсет' WHERE lemma_id = 102929;
UPDATE lemma SET lemma_stressed = 'о`сем' WHERE lemma_id = 102933;
UPDATE lemma SET lemma_stressed = 'два`йсети' WHERE lemma_id = 102955;
UPDATE lemma SET lemma_stressed = 'двана`десети' WHERE lemma_id = 102956;
UPDATE lemma SET lemma_stressed = 'двана`йсети' WHERE lemma_id = 102957;
UPDATE lemma SET lemma_stressed = 'деветна`йсети' WHERE lemma_id = 102961;
UPDATE lemma SET lemma_stressed = 'едина`йсети' WHERE lemma_id = 102964;
UPDATE lemma SET lemma_stressed = 'осемна`йсети' WHERE lemma_id = 102967;
UPDATE lemma SET lemma_stressed = 'петна`десети' WHERE lemma_id = 102971;
UPDATE lemma SET lemma_stressed = 'петна`йсети' WHERE lemma_id = 102972;
UPDATE lemma SET lemma_stressed = 'седемде`сети' WHERE lemma_id = 102973;
UPDATE lemma SET lemma_stressed = 'седемна`десети' WHERE lemma_id = 102974;
UPDATE lemma SET lemma_stressed = 'седемна`йсети' WHERE lemma_id = 102975;
UPDATE lemma SET lemma_stressed = 'три`йсети' WHERE lemma_id = 102979;
UPDATE lemma SET lemma_stressed = 'трина`йсети' WHERE lemma_id = 102981;
UPDATE lemma SET lemma_stressed = 'четири`йсети' WHERE lemma_id = 102984;
UPDATE lemma SET lemma_stressed = 'четирина`йсети' WHERE lemma_id = 102986;
UPDATE lemma SET lemma_stressed = 'шестна`йсети' WHERE lemma_id = 102990;

-- slovnik lemmata do not have fixed lemma ids
UPDATE lemma SET lemma_stressed = 'годи`на-две`' WHERE lemma = 'година-две' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'два`-три`' WHERE lemma = 'два-три' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'двай`сетина' WHERE lemma = 'двайсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'два`мка' WHERE lemma = 'двамка' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дванадесети`на' WHERE lemma = 'дванадесетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дванайсети`на' WHERE lemma = 'дванайсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'две`-три`' WHERE lemma = 'две-три' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'две`нки' WHERE lemma = 'двенки' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'две`сте' WHERE lemma = 'двесте' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'двесто`тен' WHERE lemma = 'двестотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'две`чки' WHERE lemma = 'двечки' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'двусто`тен' WHERE lemma = 'двустотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'деветми`на' WHERE lemma = 'деветмина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'деветсто`тен' WHERE lemma = 'деветстотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'де`н-два`' WHERE lemma = 'ден-два' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'де`сет-петна`десет' WHERE lemma = 'десет-петнадесет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'де`сет-петна`йсет' WHERE lemma = 'десет-петнайсет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десети`на-двана`десет' WHERE lemma = 'десетина-дванадесет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десети`на-двана`йсет' WHERE lemma = 'десетина-дванайсет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десети`на-едина`десет' WHERE lemma = 'десетина-единадесет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десети`на-едина`йсет' WHERE lemma = 'десетина-единайсет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десети`на-петна`десет' WHERE lemma = 'десетина-петнадесет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десети`на-петна`йсет' WHERE lemma = 'десетина-петнайсет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'десе`тохи`ляден' WHERE lemma = 'десетохиляден' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'еди`н-два`' WHERE lemma = 'един-два' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'еди`н-еди`нствен' WHERE lemma = 'един-единствен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'еди`н-едни`чък' WHERE lemma = 'един-едничък' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'единайсети`на' WHERE lemma = 'единайсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ле`в-два`' WHERE lemma = 'лев-два' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ма`лко' WHERE lemma = 'малко' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ми`г-два`' WHERE lemma = 'миг-два' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'милиа`рден' WHERE lemma = 'милиарден' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'милио`нен' WHERE lemma = 'милионен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мину`та-две`' WHERE lemma = 'минута-две' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мно`го' WHERE lemma = 'много' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мно`жко' WHERE lemma = 'множко' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мъ`ничко' WHERE lemma = 'мъничко' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'не`колкосто`тин' WHERE lemma = 'неколкостотин' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'нема`лко' WHERE lemma = 'немалко' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'немно`го' WHERE lemma = 'немного' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'о`семсто`тен' WHERE lemma = 'осемстотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пе`т-ше`ст' WHERE lemma = 'пет-шест' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пе`т-шести`ма' WHERE lemma = 'пет-шестима' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пе`т-шести`на' WHERE lemma = 'пет-шестина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пе`т-ше`стсто`тин' WHERE lemma = 'пет-шестстотин' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'петнайсети`на' WHERE lemma = 'петнайсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'петсто`тен' WHERE lemma = 'петстотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'по`вече' WHERE lemma = 'повече' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'по`вечко' WHERE lemma = 'повечко' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'полови`н' WHERE lemma = 'половин' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'полови`на' WHERE lemma = 'половина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пъ`рви' WHERE lemma = 'първи' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'се`дем-о`сем' WHERE lemma = 'седем-осем' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'се`демсто`тен' WHERE lemma = 'седемстотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'седми`на' WHERE lemma = 'седмина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сто`-две`ста' WHERE lemma = 'сто-двеста' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сто`тен' WHERE lemma = 'стотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'стоти`на' WHERE lemma = 'стотина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'стоти`на' WHERE lemma = 'стотина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'стоти`на-две`ста' WHERE lemma = 'стотина-двеста' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'три`-четири`ма' WHERE lemma = 'три-четирима' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'тридесети`на' WHERE lemma = 'тридесетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'трийсети`на' WHERE lemma = 'трийсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'трийсети`на' WHERE lemma = 'трийсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'три`ма' WHERE lemma = 'трима' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'три`мца' WHERE lemma = 'тримца' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'три`нки' WHERE lemma = 'тринки' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'тристо`тен' WHERE lemma = 'тристотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'три`чки' WHERE lemma = 'трички' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'тро`ица' WHERE lemma = 'троица' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хи`ляден' WHERE lemma = 'хиляден' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ча`с-два`' WHERE lemma = 'час-два' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'четво`рица' WHERE lemma = 'четворица' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'че`твърт' WHERE lemma = 'четвърт' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'четиридесети`на' WHERE lemma = 'четиридесетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'четирийсети`на' WHERE lemma = 'четирийсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'четири`ма' WHERE lemma = 'четирима' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'четирина`йсет' WHERE lemma = 'четиринайсет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'четиристо`тен' WHERE lemma = 'четиристотен' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чети`рма' WHERE lemma = 'четирма' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шейсе`т' WHERE lemma = 'шейсет' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шейсе`ти' WHERE lemma = 'шейсети' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шейсети`на' WHERE lemma = 'шейсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шестдесети`на' WHERE lemma = 'шестдесетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шести`ма' WHERE lemma = 'шестима' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шестнадесети`на' WHERE lemma = 'шестнадесетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шестнайсети`на' WHERE lemma = 'шестнайсетина' AND num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шестсто`тен' WHERE lemma = 'шестстотен' AND num_stresses = 0;

-- stress pronouns manually
UPDATE lemma SET lemma_stressed = 'ви`е' WHERE lemma_id = 102861;
UPDATE lemma SET lemma_stressed = 'то`лкав' WHERE lemma_id = 102869;
UPDATE lemma SET lemma_stressed = 'вся`къде' WHERE lemma = 'всякъде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'вся`как' WHERE lemma = 'всякак' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'вся`кога' WHERE lemma = 'всякога' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'къде`' WHERE lemma = 'къде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'къде`то' WHERE lemma = 'където' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'кога`' WHERE lemma = 'кога' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'кога`то' WHERE lemma = 'когато' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`лко' WHERE lemma = 'колко' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`лкото' WHERE lemma = 'колкото' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ни`къде' WHERE lemma = 'никъде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`къде' WHERE lemma = 'някъде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'тога`ва' WHERE lemma = 'тогава' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'то`лкова' WHERE lemma = 'толкова' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`как' WHERE lemma = 'някак' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`каква' WHERE lemma = 'някаква' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`какви' WHERE lemma = 'някакви' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`какво' WHERE lemma = 'някакво' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`кога' WHERE lemma = 'някога' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-ко`й си' WHERE lemma = 'еди-кой си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-ко`лко си' WHERE lemma = 'еди-колко си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-чи`й си' WHERE lemma = 'еди-чий си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'еди`н' WHERE lemma = 'един' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'това`-онова`' WHERE lemma = 'това-онова' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'защо`' WHERE lemma = 'защо' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'така`' WHERE lemma = 'така' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ка`кто' WHERE lemma = 'както' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`й да било`' WHERE lemma = 'кой да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`й да е' WHERE lemma = 'кой да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`й и да било`' WHERE lemma = 'кой и да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`й и да е' WHERE lemma = 'кой и да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`й-го`де' WHERE lemma = 'кой-годе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`йто да било`' WHERE lemma = 'който да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`йто да е' WHERE lemma = 'който да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`йто и да било`' WHERE lemma = 'който и да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ко`йто и да е' WHERE lemma = 'който и да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'колци`на' WHERE lemma = 'колцина' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ме`не' WHERE lemma = 'мене' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'неколци`на' WHERE lemma = 'неколцина' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'не`що' WHERE lemma = 'нещо' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ни`как' WHERE lemma = 'никак' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ни`кога' WHERE lemma = 'никога' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ни`колко' WHERE lemma = 'николко' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ня`колко' WHERE lemma = 'няколко' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'се`бе си' WHERE lemma = 'себе си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`й да било`' WHERE lemma = 'чий да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`й да е' WHERE lemma = 'чий да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`й и да било`' WHERE lemma = 'чий и да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`й и да е' WHERE lemma = 'чий и да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`й-го`де' WHERE lemma = 'чий-годе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`йто да било`' WHERE lemma = 'чийто да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`йто да е' WHERE lemma = 'чийто да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`йто и да било`' WHERE lemma = 'чийто и да било' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`йто и да е' WHERE lemma = 'чийто и да е' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'всъ`де' WHERE lemma = 'всъде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'где`то' WHERE lemma = 'гдето' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'докога`' WHERE lemma = 'докога' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'докога`то' WHERE lemma = 'докогато' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'доко`лко' WHERE lemma = 'доколко' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'доко`лкото' WHERE lemma = 'доколкото' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дони`къде' WHERE lemma = 'доникъде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'доня`къде' WHERE lemma = 'донякъде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дота`м' WHERE lemma = 'дотам' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дотога`ва' WHERE lemma = 'дотогава' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дото`лкова' WHERE lemma = 'дотолкова' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-ка`к си' WHERE lemma = 'еди-как си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-каква` си' WHERE lemma = 'еди-каква си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-какви` си' WHERE lemma = 'еди-какви си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-какво` си' WHERE lemma = 'еди-какво си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди-кога` си' WHERE lemma = 'еди-кога си' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'едно`-друго`' WHERE lemma = 'едно-друго' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'и`нак' WHERE lemma = 'инак' and num_stresses = 0;

-- stress interjections
UPDATE lemma SET lemma_stressed = 'бо`же' WHERE lemma = 'боже' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бо`жичко' WHERE lemma = 'божичко' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бо`жке' WHERE lemma = 'божке' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ва`рдааа' WHERE lemma = 'вардааа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ду`мба' WHERE lemma = 'думба' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'здраве`йте' WHERE lemma = 'здравейте' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ку`ку' WHERE lemma = 'куку' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'кю`та' WHERE lemma = 'кюта' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'лу`мба' WHERE lemma = 'лумба' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ми`ла' WHERE lemma = 'мила' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ми`нтири' WHERE lemma = 'минтири' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'му`шу' WHERE lemma = 'мушу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'па`та' WHERE lemma = 'пата' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ти`нтири' WHERE lemma = 'тинтири' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'шу`шу' WHERE lemma = 'шушу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ба`мбам' WHERE lemma = 'бамбам' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'би`би' WHERE lemma = 'биби' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'би`мба`м' WHERE lemma = 'бимбам' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'би`мба`мбу`м' WHERE lemma = 'бимбамбум' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ге`рге`р' WHERE lemma = 'гергер' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гу`гу`' WHERE lemma = 'гугу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гъ`лгъ`л' WHERE lemma = 'гългъл' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гъ`ргъ`р' WHERE lemma = 'гъргър' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гя`гя`' WHERE lemma = 'гягя' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пи`пи`' WHERE lemma = 'пипи' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пи`шпи`ш' WHERE lemma = 'пишпиш' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ади`о' WHERE lemma = 'адио' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'а`й-а`й' WHERE lemma = 'ай-ай' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'а`ла-ба`ла' WHERE lemma = 'ала-бала' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'а`ма-ха`' WHERE lemma = 'ама-ха' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ама`н' WHERE lemma = 'аман' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'а`ут' WHERE lemma = 'аут' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ба`у-ба`у' WHERE lemma = 'бау-бау' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бе`ее' WHERE lemma = 'беее' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'би`м-ба`м' WHERE lemma = 'бим-бам' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'би`м-ба`м-бу`м' WHERE lemma = 'бим-бам-бум' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'блазе`' WHERE lemma = 'блазе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бо`ц-бо`ц' WHERE lemma = 'боц-боц' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бре`-бре`' WHERE lemma = 'бре-бре' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бръ`м-бръ`м' WHERE lemma = 'бръм-бръм' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бу`м-бу`м' WHERE lemma = 'бум-бум' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ва`й-ва`й' WHERE lemma = 'вай-вай' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'взе`л-да`л' WHERE lemma = 'взел-дал' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ви`ра' WHERE lemma = 'вира' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'га`-га`' WHERE lemma = 'га-га' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'г`ааа' WHERE lemma = 'гааа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гру`х-гру`х' WHERE lemma = 'грух-грух' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гу`-гу`' WHERE lemma = 'гу-гу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гу`у' WHERE lemma = 'гуу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гъ`л-гъ`л' WHERE lemma = 'гъл-гъл' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'гъ`ци-гъ`ци' WHERE lemma = 'гъци-гъци' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'да`н-да`н' WHERE lemma = 'дан-дан' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'де-ги`ди' WHERE lemma = 'де-гиди' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'деги`ди' WHERE lemma = 'дегиди' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'де`ее' WHERE lemma = 'деее' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дру`с-дру`с' WHERE lemma = 'друс-друс' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дръ`н-дръ`н' WHERE lemma = 'дрън-дрън' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ду`м-ду`м' WHERE lemma = 'дум-дум' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ду`мба-лу`мба' WHERE lemma = 'думба-лумба' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дъ`р-дъ`р' WHERE lemma = 'дър-дър' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дъ`ра-дъ`ра' WHERE lemma = 'дъра-дъра' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ее' WHERE lemma = 'еее' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`й-е`й' WHERE lemma = 'ей-ей' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'зъ`н-зъ`н' WHERE lemma = 'зън-зън' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'и`ии' WHERE lemma = 'иии' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'и`ха' WHERE lemma = 'иха' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'и`ха-ха`' WHERE lemma = 'иха-ха' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'иха`а' WHERE lemma = 'ихаа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'и`ху' WHERE lemma = 'иху' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'и`ху-ху`' WHERE lemma = 'иху-ху' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'капу`т' WHERE lemma = 'капут' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ки`с-ки`с' WHERE lemma = 'кис-кис' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'кудкудя`к' WHERE lemma = 'кудкудяк' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'кукумя`у' WHERE lemma = 'кукумяу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'къ`л-къ`л' WHERE lemma = 'къл-къл' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'къ`т-къ`т' WHERE lemma = 'кът-кът' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'къ`ш-къ`ш' WHERE lemma = 'къш-къш' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ле`ле' WHERE lemma = 'леле' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ле`ле-ва`ре' WHERE lemma = 'леле-варе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ле`ле-ма`ле' WHERE lemma = 'леле-мале' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ма`йна' WHERE lemma = 'майна' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ма`ле' WHERE lemma = 'мале' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ма`раба' WHERE lemma = 'мараба' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ма`шала' WHERE lemma = 'машала' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ма`шалла' WHERE lemma = 'машалла' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ме`е' WHERE lemma = 'мее' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ме`ее' WHERE lemma = 'меее' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ме`рхаба' WHERE lemma = 'мерхаба' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ми`рно' WHERE lemma = 'мирно' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'му`уу' WHERE lemma = 'мууу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мя`у' WHERE lemma = 'мяу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'оке`й' WHERE lemma = 'окей' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'о`оо' WHERE lemma = 'ооо' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'о`х-ле`ле' WHERE lemma = 'ох-леле' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'па`-па`-па`' WHERE lemma = 'па-па-па' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'па`та-кю`та' WHERE lemma = 'пата-кюта' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'по`врага' WHERE lemma = 'поврага' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'приве`т' WHERE lemma = 'привет' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пръ`ждома' WHERE lemma = 'пръждома' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ра`внис' WHERE lemma = 'равнис' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сбо`гом' WHERE lemma = 'сбогом' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'свобо`дно' WHERE lemma = 'свободно' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сикти`р' WHERE lemma = 'сиктир' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сла`ва' WHERE lemma = 'слава' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'спола`йти' WHERE lemma = 'сполайти' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сст' WHERE lemma = 'сст' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'сти`га' WHERE lemma = 'стига' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'су`рва' WHERE lemma = 'сурва' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'суро`ва' WHERE lemma = 'сурова' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ти`к-та`к' WHERE lemma = 'тик-так' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ту`-ту`' WHERE lemma = 'ту-ту' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ту`йто' WHERE lemma = 'туйто' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ту`па-лу`па' WHERE lemma = 'тупа-лупа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'тупу`р-тупу`р' WHERE lemma = 'тупур-тупур' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ту`ту`' WHERE lemma = 'туту' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'у`жас' WHERE lemma = 'ужас' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'у`уу' WHERE lemma = 'ууу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'уха`' WHERE lemma = 'уха' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'уха`-ха`' WHERE lemma = 'уха-ха' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'фю`уу' WHERE lemma = 'фюуу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ха`-ха`' WHERE lemma = 'ха-ха' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ха`аа' WHERE lemma = 'хааа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хва`ла' WHERE lemma = 'хвала' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хе`-хе`' WHERE lemma = 'хе-хе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хи`-хи`' WHERE lemma = 'хи-хи' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хо`-хо`' WHERE lemma = 'хо-хо' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хо`п-тро`п' WHERE lemma = 'хоп-троп' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хъ`-хъ`' WHERE lemma = 'хъ-хъ' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хъ`к-мъ`к' WHERE lemma = 'хък-мък' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хъ`ката-мъ`ката' WHERE lemma = 'хъката-мъката' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хъ`р-мъ`р' WHERE lemma = 'хър-мър' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'цамбу`р' WHERE lemma = 'цамбур' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ца`п-ца`п' WHERE lemma = 'цап-цап' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ца`па-ца`па' WHERE lemma = 'цапа-цапа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ци`гу-ми`гу' WHERE lemma = 'цигу-мигу' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'цъ`-цъ`-цъ`' WHERE lemma = 'цъ-цъ-цъ' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'цъ`к-цъ`к' WHERE lemma = 'цък-цък' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чести`то' WHERE lemma = 'честито' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`ба' WHERE lemma = 'чиба' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чи`к-чири`к' WHERE lemma = 'чик-чирик' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чу`к-чу`к' WHERE lemma = 'чук-чук' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чу`пи-ку`пи' WHERE lemma = 'чупи-купи' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'чу`пка' WHERE lemma = 'чупка' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ъхъ`' WHERE lemma = 'ъхъ' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ъ`ъ' WHERE lemma = 'ъъ' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'я`аа' WHERE lemma = 'яаа' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'я`дец' WHERE lemma = 'ядец' and num_stresses = 0;

-- stress conjunctions
UPDATE lemma SET lemma_stressed = 'га`че' WHERE lemma = 'гаче' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'до`де' WHERE lemma = 'доде' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'доде`то' WHERE lemma = 'додето' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'загде`то' WHERE lemma = 'загдето' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'заде`то' WHERE lemma = 'задето' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ка`мо' WHERE lemma = 'камо' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'нагде`то' WHERE lemma = 'нагдето' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'про`чее' WHERE lemma = 'прочее' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'си`реч' WHERE lemma = 'сиреч' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'следова`телно' WHERE lemma = 'следователно' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'то`ест' WHERE lemma = 'тоест' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'току`' WHERE lemma = 'току' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'що`то' WHERE lemma = 'щото' and num_stresses = 0;

-- stress prepositions
UPDATE lemma SET lemma_stressed = 'спроти`' WHERE lemma = 'спроти' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'досами`' WHERE lemma = 'досами' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'зара`д' WHERE lemma = 'зарад' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'издъ`н' WHERE lemma = 'издън' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'изпомежду`' WHERE lemma = 'изпомежду' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'къ`мто' WHERE lemma = 'къмто' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мака`р' WHERE lemma = 'макар' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ми`мо' WHERE lemma = 'мимо' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ми`нус' WHERE lemma = 'минус' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'наспоре`д' WHERE lemma = 'наспоред' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'отвъ`д' WHERE lemma = 'отвъд' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'отно`сно' WHERE lemma = 'относно' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'отподи`р' WHERE lemma = 'отподир' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'отпреди`' WHERE lemma = 'отпреди' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'поди`р' WHERE lemma = 'подир' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'поди`ре' WHERE lemma = 'подире' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'по`сле' WHERE lemma = 'после' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'предви`д' WHERE lemma = 'предвид' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'пре`ко' WHERE lemma = 'преко' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'протеже`ние' WHERE lemma = 'протежение' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ра`ди' WHERE lemma = 'ради' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'съобра`зно' WHERE lemma = 'съобразно' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'я`ко' WHERE lemma = 'яко' and num_stresses = 0;

-- stress particles
UPDATE lemma SET lemma_stressed = 'а`ле' WHERE lemma = 'але' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бе`ки' WHERE lemma = 'беки' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бо`жем' WHERE lemma = 'божем' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'бо`зна' WHERE lemma = 'бозна' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'во`лю' WHERE lemma = 'волю' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'вре`ли' WHERE lemma = 'врели' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'га`че' WHERE lemma = 'гаче' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'го`де' WHERE lemma = 'годе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`ди' WHERE lemma = 'еди' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ке`шки' WHERE lemma = 'кешки' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'некипе`ли' WHERE lemma = 'некипели' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'нема`й' WHERE lemma = 'немай' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'са`нким' WHERE lemma = 'санким' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'хо`лан' WHERE lemma = 'холан' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'щя`ло' WHERE lemma = 'щяло' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'а`бе' WHERE lemma = 'абе' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'анжа`к' WHERE lemma = 'анжак' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дали`' WHERE lemma = 'дали' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'дано`' WHERE lemma = 'дано' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'е`й-ги`ди' WHERE lemma = 'ей-гиди' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'мака`р' WHERE lemma = 'макар' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'море`' WHERE lemma = 'море' and num_stresses = 0;
UPDATE lemma SET lemma_stressed = 'ха`йдете' WHERE lemma = 'хайдете' and num_stresses = 0;

-- stress lemma that are duplicated with the same stress as their siblings

-- stress the roots of disyllabic verbs by removig common prefixes and suffixes

END TRANSACTION;